import { useCallback, useEffect, useRef, useState } from 'react';

/**
 * Watches for a newer build of the app and offers to switch to it.
 *
 * The service worker is registered in `prompt` mode, so a new one installs and
 * then *waits* rather than taking over. That is deliberate: a worker that
 * activates on its own can swap the running code out from under someone who is
 * halfway through entering a transaction. This hook notices the waiting worker
 * and hands the decision to `UpdateGate`.
 *
 * `navigator.serviceWorker.controller` is the guard that separates an update
 * from a first install. On a first visit a worker installs and waits with no
 * controller to replace, and telling a first-time visitor their brand new app
 * is out of date would be nonsense.
 */
export interface AppUpdate {
  /** A newer build is installed and waiting to take over. */
  updateReady: boolean;
  /** Tell the waiting worker to take over, then reload onto it. */
  applyUpdate: () => void;
  /** True from the moment `applyUpdate` is called until the page goes. */
  applying: boolean;
}

/** How often to ask the server whether a newer build exists. */
const POLL_MS = 15 * 60 * 1000;

/**
 * If `controllerchange` never arrives — an old browser, a worker that failed
 * to activate — reload anyway rather than leaving the person stuck behind a
 * modal they cannot dismiss.
 */
const RELOAD_FALLBACK_MS = 3_000;

export const useAppUpdate = (pollMs = POLL_MS): AppUpdate => {
  const [waiting, setWaiting] = useState<ServiceWorker | null>(null);
  const [applying, setApplying] = useState(false);
  // Guards against a reload loop if `controllerchange` fires more than once.
  const reloading = useRef(false);

  useEffect(() => {
    // Test the value, not the key. In a non-secure context the `serviceWorker`
    // property exists and is undefined, so `'serviceWorker' in navigator` is
    // true and the next line throws.
    const container = typeof navigator === 'undefined' ? undefined : navigator.serviceWorker;
    if (!container) return;
    let cancelled = false;
    let registration: ServiceWorkerRegistration | undefined;
    let timer: number | undefined;

    /** A worker only counts as an update if it is replacing one. */
    const offerIfWaiting = (reg: ServiceWorkerRegistration) => {
      if (cancelled) return;
      if (reg.waiting && container.controller) setWaiting(reg.waiting);
    };

    const onUpdateFound = () => {
      const installing = registration?.installing;
      if (!installing) return;
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed' && registration) offerIfWaiting(registration);
      });
    };

    // A tab left open overnight should not keep running last week's build, and
    // coming back to a backgrounded tab is the moment a check is cheapest.
    const onVisible = () => {
      if (document.visibilityState === 'visible') void registration?.update();
    };

    void container.getRegistration().then((reg) => {
      if (cancelled || !reg) return;
      registration = reg;
      offerIfWaiting(reg);
      reg.addEventListener('updatefound', onUpdateFound);
      timer = window.setInterval(() => void reg.update(), pollMs);
      document.addEventListener('visibilitychange', onVisible);
    });

    return () => {
      cancelled = true;
      if (timer) window.clearInterval(timer);
      registration?.removeEventListener('updatefound', onUpdateFound);
      document.removeEventListener('visibilitychange', onVisible);
    };
  }, [pollMs]);

  const applyUpdate = useCallback(() => {
    if (applying) return;
    setApplying(true);

    const reload = () => {
      if (reloading.current) return;
      reloading.current = true;
      window.location.reload();
    };

    if (!waiting) {
      // Nothing is waiting but the gate is up, so the safest thing is still to
      // fetch the current build.
      reload();
      return;
    }

    navigator.serviceWorker.addEventListener('controllerchange', reload, { once: true });
    // The worker generated by vite-plugin-pwa in prompt mode listens for
    // exactly this message and calls skipWaiting().
    waiting.postMessage({ type: 'SKIP_WAITING' });
    window.setTimeout(reload, RELOAD_FALLBACK_MS);
  }, [applying, waiting]);

  return { updateReady: waiting !== null, applyUpdate, applying };
};
